import {modal,closeModal} from '../ui/modal.js';
import {toast} from '../ui/toast.js';
import {exportDatabase,downloadJSON,importDatabase,inspectBackup} from '../services/backup.js';
import {health} from '../db/health.js';
import {storageEstimate,quotaLevel} from '../db/quota.js';
import {formData,esc,$} from '../ui/dom.js';
import {APP_VERSION} from '../core/constants.js';

function dbLabel(p){return `${esc(p.displayName||'قاعدة بدون اسم')} ${p.status==='archived'?'<span class="badge">مؤرشفة</span>':''}`}
async function currentBackup(app){const data=await exportDatabase(app.ctx);downloadJSON(data,`law-office-${app.registry.active.id}-${new Date().toISOString().slice(0,10)}.json`);return data}

export async function renderDatabases(app){
  const profiles=app.registry.data.profiles,e=await storageEstimate();
  const q=e?`${quotaLevel(e)} · ${Math.round((e.usage||0)/1024/1024)} MB مستخدمة من ${Math.round((e.quota||0)/1024/1024)} MB`:'غير متاح';
  return `<div class="page-head"><div><h2>مدير قواعد البيانات</h2><p>قواعد مستقلة يمكن تبديلها وأرشفتها دون حذف بياناتها.</p></div><button class="primary" data-new-db>إنشاء قاعدة جديدة</button></div>
  <div class="notice">حالة التخزين: ${esc(q)}. إزالة القاعدة من السجل لا تحذف IndexedDB تلقائيًا.</div>
  <div class="db-grid">${profiles.map(x=>`<div class="db-card ${x.id===app.registry.data.activeProfileId?'active':''}">
    <h3>${dbLabel(x)}</h3><p>${esc(x.periodFrom||'بداية غير محددة')} ${x.periodTo?'— '+esc(x.periodTo):'— مفتوحة'}</p>
    <small>${esc(x.databaseName)}</small><div class="db-counts">${Object.entries(x.recordCounts||{}).slice(0,5).map(([k,v])=>`<span>${esc(k)}: ${v}</span>`).join('')}</div>
    <div class="db-actions"><button class="primary" data-switch-db="${x.id}" ${x.id===app.registry.data.activeProfileId?'disabled':''}>${x.id===app.registry.data.activeProfileId?'نشطة':'فتح'}</button>
    <button class="ghost" data-export-db="${x.id}">نسخة احتياطية</button><button class="ghost" data-health="${x.id}">فحص</button><button class="ghost" data-edit-db="${x.id}">تعديل</button></div></div>`).join('')}</div>`
}

async function openProfileForAction(app,id,fn){if(id===app.registry.data.activeProfileId)return fn();await app.switchDb(id);return fn()}

export function bindDatabases(app){
  document.querySelector('[data-new-db]')?.addEventListener('click',()=>newDb(app));
  document.querySelectorAll('[data-switch-db]').forEach(b=>b.onclick=async()=>{try{await app.switchDb(b.dataset.switchDb);toast('تم تبديل قاعدة البيانات');app.refresh()}catch(e){toast(e.message,'error')}});
  document.querySelectorAll('[data-export-db]').forEach(b=>b.onclick=async()=>{try{await openProfileForAction(app,b.dataset.exportDb,async()=>{await currentBackup(app);toast('تم تصدير النسخة الاحتياطية الكاملة')})}catch(e){toast(e.message,'error')}});
  document.querySelectorAll('[data-health]').forEach(b=>b.onclick=async()=>{try{await openProfileForAction(app,b.dataset.health,async()=>{const h=await health(app.ctx);app.registry.update(app.registry.active.id,{recordCounts:h.stores});showHealth(h)})}catch(e){toast(e.message,'error')}});
  document.querySelectorAll('[data-edit-db]').forEach(b=>b.onclick=()=>editDb(app,b.dataset.editDb));
}

function showHealth(h){const issueText=h.issues.length?h.issues.map(x=>`• ${x.type}: ${x.message||x.count||''}`).join('\n'):'لا توجد مشكلات مسجلة.';modal(`<div class="modal-tools"><button type="button" data-modal-back class="ghost">رجوع</button><button type="button" data-close class="modal-close">×</button></div><h2>Database Doctor</h2><p><b>${h.ok?'الحالة: سليمة مبدئيًا':'الحالة: تحتاج مراجعة'}</b></p><p>إجمالي السجلات: ${h.totalRecords}</p><h3>المشكلات</h3><pre>${esc(issueText)}</pre>${h.orphanRelations.length?`<details><summary>أول العلاقات اليتيمة</summary><pre>${esc(JSON.stringify(h.orphanRelations,null,2))}</pre></details>`:''}<button data-close class="primary">إغلاق</button>`)}

function newDb(app){const c=modal(`<div class="modal-tools"><button type="button" data-modal-back class="ghost">رجوع</button><button type="button" data-close class="modal-close">×</button></div><h2>إنشاء قاعدة بيانات</h2><form id="db-form"><label>اسم القاعدة<input name="displayName" required placeholder="مثال: ملفات 2027–2029"></label><label>من<input type="date" name="periodFrom"></label><label>إلى<input type="date" name="periodTo"></label><button class="primary">إنشاء وفتح</button></form>`);c.querySelector('form').onsubmit=async e=>{e.preventDefault();try{const p=app.registry.add(formData(e.target));await app.switchDb(p.id);closeModal();toast('تم إنشاء قاعدة البيانات');app.refresh()}catch(z){toast(z.message,'error')}}}

function editDb(app,id){const p=app.registry.data.profiles.find(x=>x.id===id);if(!p)return;const c=modal(`<div class="modal-tools"><button type="button" data-modal-back class="ghost">رجوع</button><button type="button" data-close class="modal-close">×</button></div><h2>إدارة قاعدة البيانات</h2><form id="edit-db"><label>الاسم<input name="displayName" value="${esc(p.displayName||'')}"></label><label>من<input type="date" name="periodFrom" value="${esc(p.periodFrom||'')}"></label><label>إلى<input type="date" name="periodTo" value="${esc(p.periodTo||'')}"></label><button class="primary">حفظ</button></form><hr><button class="ghost" id="archive-db">${p.status==='archived'?'إعادة تفعيل':'أرشفة القاعدة'}</button>`);c.querySelector('#edit-db').onsubmit=e=>{e.preventDefault();app.registry.update(id,formData(e.target));if(id===app.registry.data.activeProfileId)$('#db-badge').textContent=app.registry.active?.displayName||'';closeModal();app.refresh()};c.querySelector('#archive-db').onclick=()=>{try{if(id===app.registry.data.activeProfileId&&p.status!=='archived')throw Error('لا تؤرشف القاعدة النشطة قبل فتح قاعدة أخرى.');if(p.status==='archived')app.registry.activate(id);else app.registry.archive(id);closeModal();app.refresh();toast('تم تحديث حالة القاعدة')}catch(e){toast(e.message,'error')}}}

export async function renderBackup(app){return `<div class="page-head"><div><h2>النسخ الاحتياطي والاستعادة</h2><p>نسخة كاملة للقاعدة النشطة مع بصمة سلامة واستعادة آمنة.</p></div><div class="head-actions"><button class="ghost" data-page-back>رجوع</button><button class="ghost" data-page-close>إغلاق</button></div></div><div class="panel"><button class="primary" id="do-export">تصدير القاعدة الحالية</button><label class="file-input">فحص نسخة قبل الاستعادة<input id="inspect-file" type="file" accept="application/json"></label><label class="file-input">استعادة إلى قاعدة جديدة<input id="restore-new-file" type="file" accept="application/json"></label><label class="file-input">استعادة فوق القاعدة الحالية<input id="restore-file" type="file" accept="application/json"></label><div class="notice"><b>قاعدة الأمان:</b> الاستعادة إلى قاعدة جديدة هي الخيار الافتراضي الموصى به. الاستبدال فوق القاعدة الحالية لا يبدأ إلا بعد تأكيد صريح، والملف يُفحص قبل أي كتابة.</div><div id="backup-status" class="panel muted">لم يتم فحص ملف بعد.</div></div>`}

async function readJsonFile(file){try{return JSON.parse(await file.text())}catch{throw new Error('ملف النسخة ليس JSON صالحًا.')}}
async function showInspection(app,payload){const info=await inspectBackup(payload);const rows=Object.entries(info.recordCounts).filter(([,n])=>n).map(([k,n])=>`<li>${esc(k)}: ${n}</li>`).join('');modal(`<div class="modal-tools"><button type="button" data-modal-back class="ghost">رجوع</button><button type="button" data-close class="modal-close">×</button></div><h2>نتيجة فحص النسخة</h2><p>الحالة: <b>صالحة مبدئيًا</b></p><p>تاريخ التصدير: ${esc(info.exportedAt||'غير معروف')}</p><p>الإصدار: ${esc(info.applicationVersion||'غير معروف')} · Schema ${info.schemaVersion}</p><p>سلامة البصمة: ${esc(info.integrity.reason)}</p><h3>أعداد السجلات</h3><ul>${rows||'<li>لا توجد سجلات</li>'}</ul><button data-close class="primary">إغلاق</button>`)}

export function bindBackup(app){
  document.querySelector('#do-export')?.addEventListener('click',async()=>{try{await currentBackup(app);toast('تم إنشاء النسخة الاحتياطية الكاملة')}catch(e){toast(e.message,'error')}});
  document.querySelector('#inspect-file')?.addEventListener('change',async e=>{const f=e.target.files[0];if(!f)return;try{const p=await readJsonFile(f);await showInspection(app,p)}catch(z){toast(z.message,'error')}finally{e.target.value=''}});
  document.querySelector('#restore-new-file')?.addEventListener('change',async e=>{const f=e.target.files[0];if(!f)return;try{const p=await readJsonFile(f);const info=await inspectBackup(p);const name=prompt('اسم قاعدة الاستعادة الجديدة:',`مستعادة ${String(p.exportedAt||'').slice(0,10)}`);if(!name?.trim())return;const previousId=app.registry.data.activeProfileId;const profile=app.registry.add({displayName:name.trim(),periodFrom:p.database?.periodFrom||null,periodTo:p.database?.periodTo||null,status:'active'});app.registry.data.activeProfileId=previousId;app.registry.save();try{await importIntoNewProfile(app,profile,p);app.registry.update(profile.id,{recordCounts:info.recordCounts,schemaVersion:info.schemaVersion,applicationVersion:APP_VERSION});app.registry.log('database:restored-to-new',{profileId:profile.id,sourceExportedAt:p.exportedAt});$('#db-badge').textContent=profile.displayName;toast('تمت الاستعادة إلى قاعدة جديدة دون المساس بالقاعدة الحالية');app.refresh()}catch(err){app.registry.update(profile.id,{status:'archived',recoveryFailed:true});app.registry.data.activeProfileId=previousId;app.registry.save();throw err}}catch(z){toast(z.message||'فشلت الاستعادة إلى قاعدة جديدة','error')}finally{e.target.value=''}});
  document.querySelector('#restore-file')?.addEventListener('change',async e=>{const f=e.target.files[0];if(!f)return;try{const p=await readJsonFile(f);const info=await inspectBackup(p);const current=await exportDatabase(app.ctx);const ok=confirm(`استعادة فوق القاعدة الحالية «${app.registry.active.displayName}».\n\nسيتم حذف محتوى القاعدة الحالية واستبداله بـ ${Object.values(info.recordCounts).reduce((a,b)=>a+b,0)} سجلًا.\nتم فحص النسخة: ${info.integrity.reason}\n\nهل أخذت نسخة احتياطية من القاعدة الحالية؟\nاضغط موافق للمتابعة.`);if(!ok)return;downloadJSON(current,`law-office-pre-restore-${app.registry.active.id}-${Date.now()}.json`);await importDatabase(app.ctx,p,{mode:'replace'});app.registry.update(app.registry.active.id,{recordCounts:info.recordCounts});app.registry.log('database:restored-in-place',{exportedAt:p.exportedAt});toast('تمت الاستعادة بنجاح بعد إنشاء نسخة أمان من القاعدة الحالية');app.refresh()}catch(z){toast(z.message||'فشلت الاستعادة ولم يتم اعتماد التغيير','error')}finally{e.target.value=''}})
}

async function importIntoNewProfile(app,profile,payload){
  // Import into the new database first, then switch the app to it through the manager (closes the old connection).
  const tmp=await app.manager.open(profile,{makeCurrent:false});
  try{await importDatabase(tmp,payload,{mode:'replace'})}finally{tmp.close()}
  await app.switchDb(profile.id);
}

export function renderRecovery(candidates){return `<div class="panel"><h2>استعادة سجل قواعد البيانات</h2><p>تعذر قراءة سجل قواعد البيانات المحلي. لم يتم حذف قواعد IndexedDB نفسها.</p><div class="notice">اختر قاعدة موجودة لاعتمادها من جديد، أو ابدأ سجلًا جديدًا إذا لم توجد قاعدة قابلة للاسترداد.</div>${candidates.length?`<div class="db-grid">${candidates.map((x,i)=>`<div class="db-card"><h3>قاعدة مكتشفة ${i+1}</h3><p><code>${esc(x.databaseName)}</code></p><p>الإصدار: ${x.version}</p><button class="primary" data-adopt-db="${esc(x.databaseName)}">اعتماد هذه القاعدة</button></div>`).join('')}</div>`:'<p class="muted">لم يتمكن المتصفح من كشف قواعد موجودة تلقائيًا.</p>'}<hr><button class="ghost" data-new-registry>بدء سجل قواعد جديد</button></div>`}
export function bindRecovery(app,candidates){document.querySelectorAll('[data-adopt-db]').forEach(b=>b.onclick=async()=>{try{const x=candidates.find(c=>c.databaseName===b.dataset.adoptDb);if(!x)throw Error('قاعدة البيانات غير موجودة في نتائج الفحص.');app.registry.adoptExisting(x);app.setContext(await app.manager.openActive());toast('تم اعتماد قاعدة البيانات');await app.go('dashboard')}catch(e){toast(e.message,'error')}});document.querySelector('[data-new-registry]')?.addEventListener('click',async()=>{if(!confirm('سيتم إنشاء سجل جديد دون حذف قواعد IndexedDB الموجودة. هل تريد المتابعة؟'))return;try{app.registry.resetRegistry();app.setContext(await app.manager.openActive());toast('تم إنشاء سجل جديد');await app.go('dashboard')}catch(e){toast(e.message,'error')}})}
