import {STORE} from '../db/schema.js';
import {esc,formData} from '../ui/dom.js';
import {modal,closeModal} from '../ui/modal.js';
import {toast} from '../ui/toast.js';
import {saveOperational} from '../services/operations.js';
import {pager} from '../ui/pagination.js';
import {lookupField,bindLookups} from '../ui/lookup.js';

const configs={
 hearings:{title:'الجلسات',desc:'تسجيل ما تم في الجلسة وربطه بالقضية والخطوة التالية.',fields:['caseId','hearingDate','hearingTime','type','reason','whatHappened','decision','result','nextAction','nextHearingDate','notes'],wide:['whatHappened','decision','notes'],index:'hearingDate'},
 procedures:{title:'الإجراءات والمهام',desc:'متابعة الأعمال الداخلية والإجراءات المرتبطة بالملفات والقضايا.',fields:['fileId','caseId','type','description','actionDate','assigneeId','status','priority','internalDueDate','nextAction','notes'],wide:['description','notes'],index:'internalDueDate'},
 appointments:{title:'المواعيد',desc:'مواعيد المكتب والعملاء والاجتماعات المرتبطة بالملفات.',fields:['fileId','clientId','title','date','time','location','type','status','notes'],wide:['notes'],index:'date'},
 communications:{title:'الاتصالات',desc:'سجل اتصالات المكتب مع العملاء والمتابعة المطلوبة.',fields:['clientId','fileId','channel','direction','subject','summary','date','followUpRequired','followUpDate'],wide:['summary'],index:'date'},
 caseNotes:{title:'ملاحظات القضايا',desc:'ملاحظات تشغيلية مرتبطة بملف القضية.',fields:['fileId','category','content'],wide:['content'],index:'createdAt'}
};
const labels={caseId:'القضية',fileId:'الملف',clientId:'الموكل',hearingDate:'تاريخ الجلسة',hearingTime:'وقت الجلسة',type:'النوع',reason:'سبب الجلسة',whatHappened:'ما تم في الجلسة',decision:'القرار/ما قضت به المحكمة',result:'النتيجة',nextAction:'الإجراء التالي',nextHearingDate:'الجلسة القادمة',notes:'ملاحظات',description:'وصف الإجراء',actionDate:'تاريخ الإجراء',assigneeId:'المسؤول',status:'الحالة',priority:'الأولوية',internalDueDate:'موعد المتابعة',title:'عنوان الموعد',date:'التاريخ',time:'الوقت',location:'المكان',channel:'وسيلة الاتصال',direction:'الاتجاه',subject:'الموضوع',summary:'ملخص الاتصال',followUpRequired:'تحتاج متابعة',followUpDate:'تاريخ المتابعة',category:'التصنيف'};
const escv=v=>esc(v??'');

export async function operationsPage(app,store){
 const cfg=configs[store]; app.__opPages=app.__opPages||{}; const state=app.__opPages[store]||{page:1,cursor:null,filters:{q:'',status:'',priority:'',from:'',to:'',sort:'desc'}}; app.__opPages[store]=state;
 const f=state.filters||{}; const filter=v=>{const q=String(f.q||'').trim().toLowerCase();const d=String(v.updatedAt||v.actionDate||v.internalDueDate||v.date||v.createdAt||'').slice(0,10);const hay=JSON.stringify(v).toLowerCase();return (!q||hay.includes(q))&&(!f.status||v.status===f.status)&&(!f.priority||v.priority===f.priority)&&(!f.from||d>=f.from)&&(!f.to||d<=f.to)}; const r=await app.office.r[store].page({index:cfg.index,cursor:state.cursor,limit:25,direction:(f.sort==='asc'?'next':(state.direction||'prev')),filter}); state.nextCursor=r.nextCursor; state.hasNext=r.hasMore; state.hasPrev=state.page>1;
 const ctx=await contextMaps(app,store,r.items);
 return `<div class="page-head"><div><h2>${cfg.title}</h2><p>${cfg.desc}</p></div><div class="head-actions"><button class="ghost" data-page-back>رجوع</button><button class="ghost" data-page-close>إغلاق</button><button class="primary" data-op-add="${store}">إضافة</button></div>
 <div class="toolbar"><input id="op-q" value="${escv(f.q||'')}" placeholder="بحث في جميع السجلات…"><details class="filter-tab"><summary>فرز وتصفية</summary><div class="mini-filter"><select id="op-status"><option value="">كل الحالات</option><option>open</option><option>pending</option><option>done</option><option>cancelled</option></select><select id="op-priority"><option value="">كل الأولويات</option><option>normal</option><option>urgent</option><option>critical</option></select><input id="op-from" type="date"><input id="op-to" type="date"><select id="op-sort"><option value="desc" ${f.sort==='desc'?'selected':''}>الأحدث أولًا</option><option value="asc" ${f.sort==='asc'?'selected':''}>الأقدم أولًا</option></select></div></details><span class="muted">صفحة ${state.page} — 25 كحد أقصى</span></div>
 <div class="table-wrap"><table><thead><tr>${columns(store).map(x=>`<th>${labels[x]||x}</th>`).join('')}<th>إجراءات</th></tr></thead><tbody id="op-body">${r.items.map(x=>rowHtml(store,x,ctx)).join('')}</tbody></table></div>${pager({page:state.page,hasNext:r.hasMore,hasPrev:state.hasPrev})}`;
}
function columns(store){return {hearings:['caseId','hearingDate','hearingTime','reason','result'],procedures:['fileId','description','internalDueDate','status','priority'],appointments:['title','date','time','location','status'],communications:['clientId','subject','channel','date','followUpRequired'],caseNotes:['fileId','category','content']}[store]}
function rowHtml(store,r,ctx){return `<tr data-status="${escv(r.status||'')}" data-priority="${escv(r.priority||'')}" data-date="${escv(r.updatedAt||r.actionDate||r.internalDueDate||r.date||'')}" data-search="${escv(JSON.stringify(r))}">${columns(store).map(f=>`<td>${display(f,r[f],ctx)}</td>`).join('')}<td><button class="link" data-op-edit="${store}|${r.id}">فتح</button></td></tr>`}
function display(f,v,ctx){if(['caseId','fileId','clientId'].includes(f))return escv(ctx[f]?.get(v)||'—');if(f==='hearingDate'||f==='nextHearingDate'||f==='date'||f==='internalDueDate'||f==='actionDate'||f==='followUpDate')return escv(v);return escv(String(v||'').slice(0,90)||'—')}
async function contextMaps(app,store,rows){const m={};for(const key of ['caseId','fileId','clientId']){const ids=[...new Set(rows.map(r=>r[key]).filter(Boolean))];if(!ids.length)continue;const target=key==='caseId'?STORE.cases:key==='fileId'?STORE.files:STORE.clients;const x=await app.office.r[target].getMany(ids);m[key]=new Map(x.map(r=>[r.id,key==='caseId'?`${r.caseNumber||''}/${r.caseYear||''} — ${r.courtId||''}`:key==='fileId'?`${r.fileNumber||''} — ${r.title||''}`:r.fullName||'' ]))}return m}

export async function bindOperations(app,store){
 document.querySelector(`[data-op-add="${store}"]`)?.addEventListener('click',()=>operationForm(app,store));
 document.querySelectorAll('[data-op-edit]').forEach(b=>b.onclick=()=>{const [s,id]=b.dataset.opEdit.split('|');operationForm(app,s,id)});
 document.querySelector('[data-pager-next]')?.addEventListener('click',()=>{const s=app.__opPages[store];s.cursor=s.nextCursor;s.page++;app.refresh()});
 document.querySelector('[data-pager-prev]')?.addEventListener('click',()=>{const s=app.__opPages[store];if(!s?.hasPrev)return;s.cursor=s.prevCursor;s.page--;s.direction='prev';app.refresh()});
 ['op-q','op-status','op-priority','op-from','op-to','op-sort'].forEach(id=>document.querySelector('#'+id)?.addEventListener('input',filterOps));document.querySelectorAll('#op-status,#op-priority,#op-sort').forEach(x=>x.addEventListener('change',filterOps));
 function filterOps(){const st=app.__opPages[store];st.filters={q:document.querySelector('#op-q')?.value||'',status:document.querySelector('#op-status')?.value||'',priority:document.querySelector('#op-priority')?.value||'',from:document.querySelector('#op-from')?.value||'',to:document.querySelector('#op-to')?.value||'',sort:document.querySelector('#op-sort')?.value||'desc'};st.page=1;st.cursor=null;st.direction='next';app.refresh()}
}
async function operationForm(app,store,id=null){
 const cfg=configs[store],old=id?await app.office.r[store].get(id):{};const maps=await contextMaps(app,store,id?[old]:[]);
 const c=modal(`<div class="modal-tools"><button type="button" data-modal-back class="ghost">رجوع</button><button type="button" data-close class="modal-close">×</button></div><h2>${id?'تعديل':'إضافة'} — ${cfg.title}</h2><form>${cfg.fields.map(f=>fieldHtml(f,old,maps,cfg.wide.includes(f))).join('')}<button class="primary">حفظ</button></form>`);bindLookups(c,app.office);
 c.querySelector('form').onsubmit=async e=>{e.preventDefault();try{await saveOperational(app.office,store,formData(e.target),id);closeModal();toast('تم الحفظ وتحديث سجل النشاط');app.refresh()}catch(x){toast(x.message||'تعذر الحفظ','error')}};
}
function fieldHtml(f,old,maps,wide){const value=old?.[f]??'';if(f==='caseId'){const m=maps.caseId||new Map();return lookupField({name:'caseId',label:labels[f],store:'cases',index:'caseNumber',value,displayValue:m.get(value)||''})}if(f==='fileId'){const m=maps.fileId||new Map();return lookupField({name:'fileId',label:labels[f],store:'files',index:'fileNumber',value,displayValue:m.get(value)||''})}if(f==='clientId'){const m=maps.clientId||new Map();return lookupField({name:'clientId',label:labels[f],store:'clients',index:'fullNameNormalized',value,displayValue:m.get(value)||''})}if(f==='followUpRequired')return `<label>${labels[f]}<select name="${f}"><option value="false" ${value!==true?'selected':''}>لا</option><option value="true" ${value===true?'selected':''}>نعم</option></select></label>`;if(f==='status')return `<label>${labels[f]}<select name="${f}">${['open','pending','done','cancelled'].map(x=>`<option ${x===(value||'open')?'selected':''}>${x}</option>`).join('')}</select></label>`;if(f==='priority')return `<label>${labels[f]}<select name="${f}">${['normal','urgent','critical'].map(x=>`<option ${x===(value||'normal')?'selected':''}>${x}</option>`).join('')}</select></label>`;const area=wide||['notes','reason','nextAction'].includes(f);const type=/Date$|^date$|^actionDate$|^internalDueDate$/.test(f)?'date':f==='hearingTime'||f==='time'?'time':'text';return `<label>${labels[f]||f}${area?`<textarea name="${f}">${escv(value)}</textarea>`:`<input name="${f}" type="${type}" value="${escv(value)}">`}</label>`}
