import {pager} from '../ui/pagination.js';
import {lookupField,bindLookups} from '../ui/lookup.js';
import {STORE} from '../db/schema.js';import {esc,formData} from '../ui/dom.js';import {normalizeArabic} from '../core/search-normalizer.js';import {modal,closeModal} from '../ui/modal.js';import {toast} from '../ui/toast.js';
const date=v=>v?new Date(v).toLocaleDateString('ar-EG'):'';
export async function dashboard(app){
 const {dashboardBrief}=await import('../services/dashboard.js');
 const r=await dashboardBrief(app.office);
 const d=v=>v?new Date(v).toLocaleDateString('ar-EG'):'';
 return `<div class="hero"><div><h2>صباح الخير، مكتب الأستاذ أحمد محمد خضير</h2><p>لوحة العمل اليومية والأسبوعية — الجلسات والأعمال التي تحتاج إلى متابعة.</p></div><div class="head-actions"><button class="ghost" data-back>رجوع</button><button class="primary" data-quick="file">+ فتح ملف جديد</button><button class="ghost" data-route="actionCenter">مركز العمل</button></div></div>
 <div class="dashboard-grid">
  <section class="panel priority-panel"><div class="panel-head"><h3>جلسات اليوم</h3><button class="link" data-dashboard-report="hearings|today">تقرير الجلسات</button></div>${r.todayHearings.length?r.todayHearings.slice(0,12).map(x=>`<div class="work-row"><b>${esc(x.hearingTime||'بدون وقت')}</b><span>${esc(x.reason||x.type||'جلسة')}</span><small>${d(x.hearingDate)}</small></div>`).join(''):'<p class="muted">لا توجد جلسات مسجلة اليوم.</p>'}</section>
  <section class="panel"><div class="panel-head"><h3>الأعمال الإدارية المتأخرة</h3><button class="link" data-dashboard-report="procedures|overdue">تقرير الأعمال</button></div>${r.overdueProcedures.length?r.overdueProcedures.slice(0,12).map(x=>`<div class="work-row"><b>${esc(x.internalDueDate||'')}</b><span>${esc(x.description||x.type||'إجراء')}</span><small>${esc(x.priority||'normal')}</small></div>`).join(''):'<p class="muted">لا توجد أعمال إدارية متأخرة.</p>'}</section>
  <section class="panel"><div class="panel-head"><h3>الجلسات القادمة</h3><button class="link" data-dashboard-report="hearings|week">هذا الأسبوع</button></div>${r.upcomingHearings.length?r.upcomingHearings.slice(0,12).map(x=>`<div class="work-row"><b>${d(x.hearingDate)}</b><span>${esc(x.hearingTime||'')} — ${esc(x.reason||x.type||'جلسة')}</span><small>${esc(x.caseNumber||'')}</small></div>`).join(''):'<p class="muted">لا توجد جلسات قادمة ضمن الفترة المعروضة.</p>'}</section>
  <section class="panel"><div class="panel-head"><h3>أعمال إدارية قادمة</h3><button class="link" data-dashboard-report="procedures|week">هذا الأسبوع</button></div>${r.upcomingProcedures.length?r.upcomingProcedures.slice(0,12).map(x=>`<div class="work-row"><b>${d(x.internalDueDate)}</b><span>${esc(x.description||x.type||'إجراء')}</span><small>${esc(x.status||'pending')}</small></div>`).join(''):'<p class="muted">لا توجد أعمال إدارية قادمة ضمن الفترة المعروضة.</p>'}</section>
 </div>
 <section class="panel daily-shortcuts"><div class="panel-head"><h3>تقارير العمل السريع</h3></div><div class="shortcut-grid"><button data-dashboard-report="hearings|tomorrow">جلسات غدًا</button><button data-dashboard-report="hearings|nextWeek">جلسات الأسبوع التالي</button><button data-dashboard-report="hearings|month">جلسات هذا الشهر</button><button data-dashboard-report="procedures|tomorrow">أعمال غدًا</button><button data-dashboard-report="procedures|nextWeek">أعمال الأسبوع التالي</button><button data-dashboard-report="procedures|month">أعمال هذا الشهر</button><button data-route-report="clients">الموكلون</button><button data-route-report="cases">القضايا</button></div></section></div>`
}
export async function clients(app){return pagedEntityPage(app,{store:STORE.clients,title:'الموكلون',description:'بيانات الموكلين في قاعدة البيانات الحالية.',addAttr:'data-add-client',addText:'إضافة موكل',index:'createdAt',sort:'createdAt',render:clientTable})}
export async function files(app){return pagedEntityPage(app,{store:STORE.files,title:'الملفات',description:'الوحدة الإدارية الرئيسية لدورة العمل القانوني.',addAttr:'data-add-file',addText:'فتح ملف',index:'lastActivityAt',sort:'lastActivityAt',render:fileTable})}
export async function cases(app){return pagedEntityPage(app,{store:STORE.cases,title:'القضايا',description:'الوحدات القضائية المرتبطة بالملفات.',addAttr:'data-add-case',addText:'إضافة قضية',index:'filingDate',sort:'filingDate',render:caseTable})}
async function pagedEntityPage(app,cfg){const state=app.__pages?.[cfg.store]||{page:1,cursor:null,prevCursor:null,filters:{q:'',status:'',priority:'',from:'',to:'',sort:'asc'}};app.__pages=app.__pages||{};app.__pages[cfg.store]=state;state.filters=state.filters||{q:'',status:'',priority:'',from:'',to:'',sort:'asc'};const f=state.filters;const filter=v=>{const text=normalizeArabic([v.fullName,v.phone,v.phone1,v.fileNumber,v.title,v.caseNumber,v.subject,v.courtId].filter(Boolean).join(' '));const q=normalizeArabic(f.q);const ds=String(v.updatedAt||v.lastActivityAt||v.filingDate||v.createdAt||'').slice(0,10);return (!q||text.includes(q))&&(!f.status||v.status===f.status)&&(!f.priority||v.priority===f.priority)&&(!f.from||ds>=f.from)&&(!f.to||ds<=f.to)};const r=await app.office.listPage(cfg.store,{index:cfg.index,cursor:state.cursor,limit:25,direction:(f.sort==='desc'?'prev':(state.direction||'next')),filter});state.hasNext=r.hasMore;state.hasPrev=state.page>1;state.prevCursor=r.prevCursor;state.nextCursor=r.nextCursor;state.direction='next';return `<div class="page-head"><div><h2>${cfg.title}</h2><p>${cfg.description}</p></div><div class="head-actions"><button class="ghost" data-page-back>رجوع</button><button class="ghost" data-page-close>إغلاق</button><button class="primary" ${cfg.addAttr}>${cfg.addText}</button></div><div class="toolbar"><input id="${cfg.store}-q" placeholder="بحث سريع…"><details class="filter-tab"><summary>فرز وتصفية</summary><div class="mini-filter"><select data-filter-status><option value="">كل الحالات</option><option>active</option><option>inactive</option><option>open</option><option>closed</option><option>pending</option><option>done</option></select><select data-filter-priority><option value="">كل الأولويات</option><option>normal</option><option>urgent</option><option>critical</option></select><input type="date" data-filter-from><input type="date" data-filter-to><select data-filter-sort><option value="asc" ${f.sort==='asc'?'selected':''}>الأقدم أولًا</option><option value="desc" ${f.sort==='desc'?'selected':''}>الأحدث أولًا</option></select></div></details></div><div id="${cfg.store}-list" class="table-wrap">${cfg.render(r.items)}</div>${pager({page:state.page,hasNext:r.hasMore,hasPrev:state.page>1})}`}
function clientTable(rows){return `<table><thead><tr><th>الاسم</th><th>الهاتف</th><th>الحالة</th><th>آخر تحديث</th><th></th></tr></thead><tbody>${rows.map(r=>`<tr data-status="${esc(r.status||'')}" data-date="${esc(r.updatedAt||'')}" data-search="${esc((r.fullName||'')+' '+(r.phone||r.phone1||''))}"><td><b>${esc(r.fullName)}</b></td><td>${esc(r.phone||r.phone1||'')}</td><td><span class="badge">${esc(r.status||'active')}</span></td><td>${date(r.updatedAt)}</td><td><button class="link" data-record-client="${r.id}">سجل</button> <button class="link" data-edit-client="${r.id}">تعديل</button></td></tr>`).join('')}</tbody></table>`}
function fileTable(rows){return `<table><thead><tr><th>رقم الملف</th><th>العنوان</th><th>الحالة</th><th>الأولوية</th><th>آخر نشاط</th><th></th></tr></thead><tbody>${rows.map(r=>`<tr data-status="${esc(r.status||'')}" data-priority="${esc(r.priority||'')}" data-date="${esc(r.lastActivityAt||'')}" data-search="${esc((r.fileNumber||'')+' '+(r.title||''))}"><td><b>${esc(r.fileNumber)}</b></td><td>${esc(r.title)}</td><td><span class="badge">${esc(r.status||'open')}</span></td><td>${esc(r.priority||'normal')}</td><td>${date(r.lastActivityAt)}</td><td><button class="link" data-record-file="${r.id}">سجل</button> <button class="link" data-edit-file="${r.id}">تعديل</button></td></tr>`).join('')}</tbody></table>`}
function caseTable(rows){return `<table><thead><tr><th>رقم/سنة</th><th>المحكمة</th><th>الموضوع</th><th>الحالة</th><th></th></tr></thead><tbody>${rows.map(r=>`<tr data-status="${esc(r.status||'')}" data-date="${esc(r.filingDate||'')}" data-search="${esc((r.caseNumber||'')+' '+(r.subject||'')+' '+(r.courtId||''))}"><td><b>${esc(r.caseNumber)}</b> / ${esc(r.caseYear)}</td><td>${esc(r.courtId||'')}</td><td>${esc(r.subject||'')}</td><td><span class="badge">${esc(r.status||'open')}</span></td><td><button class="link" data-record-case="${r.id}">سجل</button> <button class="link" data-edit-case="${r.id}">تعديل</button></td></tr>`).join('')}</tbody></table>`}
export async function search(app){return `<div class="page-head"><div><h2>البحث الموحد</h2><p>البحث في الموكلين والملفات والقضايا والخصوم.</p></div></div><div class="search-box"><input id="global-q" autofocus placeholder="اكتب اسمًا أو رقمًا أو عنوانًا…"><div id="search-results"></div></div>`}
export async function genericPage(app,store,title){
 const fields={hearings:['caseId','hearingDate','hearingTime','reason','result'],procedures:['description','actionDate','internalDueDate','status','priority'],appointments:['title','date','time','location','status'],communications:['channel','direction','subject','date','summary'],caseNotes:['category','content'],opponents:['name','capacity','phone','address'],powersOfAttorney:['poaNumber','type','issuedDate','expiryDate','scope'],witnesses:['name','side','phone','address'],expertReports:['expertName','reportDate','summary'],judgments:['judgmentNumber','court','judgmentDate','operativeSummary'],execution:['executionNumber','status','stage','openedDate'],fees:['agreementType','agreedAmount','currency','paymentStatus'],feePayments:['feeId','amount','date'],documentReferences:['title','type','physicalLocation','date']}[store]||['title','date','status','notes'];
 const indexMap={hearings:'hearingDate',procedures:'internalDueDate',appointments:'date',communications:'date',caseNotes:'createdAt',opponents:'nameNormalized',powersOfAttorney:'issuedDate',witnesses:'createdAt',expertReports:'reportDate',judgments:'judgmentDate',execution:'openedDate',fees:'createdAt',feePayments:'date',documentReferences:'date'};
 const state=app.__genericPages?.[store]||{page:1,cursor:null,direction:'next'};app.__genericPages=app.__genericPages||{};app.__genericPages[store]=state;
 const r=await app.office.listPage(store,{index:indexMap[store],cursor:state.cursor,limit:25,direction:state.direction});state.hasNext=r.hasMore;state.hasPrev=state.page>1;state.nextCursor=r.nextCursor;state.prevCursor=r.prevCursor;state.direction='next';
 return `<div class="page-head"><div><h2>${title}</h2><p>صفحة ${state.page} · يتم تحميل السجلات المطلوبة فقط.</p></div><div class="head-actions"><button class="ghost" data-page-back>رجوع</button><button class="ghost" data-page-close>إغلاق</button><button class="primary" data-generic-add="${store}">إضافة</button></div><div class="table-wrap"><table><thead><tr>${fields.map(f=>`<th>${esc(f)}</th>`).join('')}<th></th></tr></thead><tbody>${r.items.map(x=>`${fields.map(f=>`<td>${esc(x[f])}</td>`).join('')}<td><button class="link" data-generic-edit="${store}|${x.id}">تعديل</button></td>`).join('')}</tbody></table></div>${pager({page:state.page,hasNext:r.hasMore,hasPrev:state.page>1})}`}
export function bindGenericPagePagination(app,store){const st=app.__genericPages?.[store];document.querySelector('[data-pager-next]')?.addEventListener('click',()=>{if(!st?.hasNext)return;st.page++;st.cursor=st.nextCursor;st.direction='next';app.refresh()});document.querySelector('[data-pager-prev]')?.addEventListener('click',()=>{if(!st?.hasPrev)return;st.page--;st.cursor=st.prevCursor;st.direction='prev';app.refresh()})}
export function bindDashboard(app){
 document.querySelector('[data-quick=\"file\"]')?.addEventListener('click',()=>app.go('files'));
 document.querySelector('[data-back]')?.addEventListener('click',()=>app.back());
 document.querySelectorAll('[data-dashboard-report]').forEach(b=>b.onclick=()=>{const [type,preset]=b.dataset.dashboardReport.split('|');app.go('reports?type='+encodeURIComponent(type)+'&preset='+encodeURIComponent(preset))});
 document.querySelectorAll('[data-route-report]').forEach(b=>b.onclick=()=>app.go('reports?type='+encodeURIComponent(b.dataset.routeReport)));
}
export function bindPages(app){
 document.querySelectorAll("[data-page-back]").forEach(b=>b.onclick=()=>app.back());document.querySelectorAll("[data-page-close]").forEach(b=>b.onclick=()=>app.go("dashboard"));
 document.querySelector('[data-back]')?.addEventListener('click',()=>app.back());
 document.querySelector('[data-add-client]')?.addEventListener('click',()=>clientForm(app));document.querySelector('[data-add-file]')?.addEventListener('click',()=>fileForm(app));document.querySelector('[data-add-case]')?.addEventListener('click',()=>caseForm(app));
 bindRecordButtons(app);document.querySelectorAll('[data-edit-client]').forEach(b=>b.onclick=()=>clientForm(app,b.dataset.editClient));document.querySelectorAll('[data-edit-file]').forEach(b=>b.onclick=()=>fileForm(app,b.dataset.editFile));document.querySelectorAll('[data-edit-case]').forEach(b=>b.onclick=()=>caseForm(app,b.dataset.editCase));
 const store=app.route.split('?')[0];
 const q=document.querySelector('#'+store+'-q');q?.addEventListener('input',()=>{const st=app.__pages[store];st.filters.q=q.value;st.page=1;st.cursor=null;st.direction='next';app.refresh()});
 bindListFilter('#'+store+'-list',app,store);
 document.querySelector('[data-pager-next]')?.addEventListener('click',()=>{const st=app.__pages[store];if(!st?.hasNext)return;st.page++;st.cursor=st.nextCursor;st.direction='next';app.refresh()});
 document.querySelector('[data-pager-prev]')?.addEventListener('click',()=>{const st=app.__pages[store];if(!st?.hasPrev)return;st.page--;st.cursor=st.prevCursor;st.direction='prev';app.refresh()});
}
function bindRecordButtons(app){document.querySelectorAll('[data-record-client]').forEach(b=>b.onclick=()=>app.go('client:'+b.dataset.recordClient));document.querySelectorAll('[data-record-file]').forEach(b=>b.onclick=()=>app.go('file:'+b.dataset.recordFile));document.querySelectorAll('[data-record-case]').forEach(b=>b.onclick=()=>app.go('case:'+b.dataset.recordCase))}
function bindListFilter(sel,app,store){document.querySelectorAll('.filter-tab select,.filter-tab input').forEach(el=>{const key=el.dataset.filterStatus?'status':el.dataset.filterPriority?'priority':el.dataset.filterFrom?'from':el.dataset.filterTo?'to':'sort';el.value=app.__pages[store].filters[key]||'';el.addEventListener('change',()=>{const st=app.__pages[store];st.filters[key]=el.value;st.page=1;st.cursor=null;st.direction='next';app.refresh()});el.addEventListener('input',()=>{const st=app.__pages[store];st.filters[key]=el.value;st.page=1;st.cursor=null;st.direction='next';app.refresh()})})}
function localFilter(sel,q){const n=String(q||'').trim().toLowerCase();document.querySelectorAll(sel+' tbody tr').forEach(tr=>tr.hidden=n&&!tr.textContent.toLowerCase().includes(n))}
function clientForm(app,id){const old=id?app.office.r.clients.get(id):Promise.resolve({});old.then(x=>{const c=modal(`<div class="modal-tools"><button type="button" data-modal-back class="ghost">رجوع</button><button type="button" data-close class="modal-close">×</button></div><h2>${id?'تعديل':'إضافة'} موكل</h2><form id="client-form"><label>الاسم الكامل<input name="fullName" required value="${esc(x.fullName||'')}"></label><label>الرقم القومي<input name="nationalId" inputmode="numeric" value="${esc(x.nationalId||'')}"></label><label>الهاتف<input name="phone" type="tel" value="${esc(x.phone||'')}"></label><label>العنوان<textarea name="address">${esc(x.address||'')}</textarea></label><label>المهنة<input name="profession" value="${esc(x.profession||'')}"></label><label>الحالة<select name="status"><option value="active" ${x.status==='active'?'selected':''}>نشط</option><option value="inactive" ${x.status==='inactive'?'selected':''}>غير نشط</option></select></label><label>ملاحظات<textarea name="notes">${esc(x.notes||'')}</textarea></label><button class="primary">حفظ</button></form>`);bindLookups(c,app.office);c.querySelector('form').onsubmit=async e=>{e.preventDefault();try{await app.office.saveClient(formData(e.target),id);closeModal();toast('تم حفظ الموكل');app.refresh()}catch(z){toast(z.message,'error')}}})}
async function fileForm(app,id){const old=id?await app.office.r.files.get(id):{};const c=modal(`<div class="modal-tools"><button type="button" data-modal-back class="ghost">رجوع</button><button type="button" data-close class="modal-close">×</button></div><h2>${id?'تعديل':'فتح'} ملف</h2><form id="file-form"><label>عنوان الملف<input name="title" required value="${esc(old.title||'')}"></label><label>نوع العمل<input name="workType" value="${esc(old.workType||'')}"></label><label>الحالة<select name="status"><option value="open">مفتوح</option><option value="closed" ${old.status==='closed'?'selected':''}>مغلق</option></select></label><label>المرحلة<input name="stage" value="${esc(old.stage||'')}"></label><label>الأولوية<select name="priority"><option>normal</option><option ${old.priority==='urgent'?'selected':''}>urgent</option><option ${old.priority==='critical'?'selected':''}>critical</option></select></label><label>تاريخ الفتح<input type="date" name="openedAt" value="${esc(old.openedAt||new Date().toISOString().slice(0,10))}"></label><label>الخطوة التالية<input name="nextStep" value="${esc(old.nextStep||'')}"></label><label>تاريخ الخطوة التالية<input type="date" name="nextStepDate" value="${esc(old.nextStepDate||'')}"></label><label>ملاحظات<textarea name="notes">${esc(old.notes||'')}</textarea></label><button class="primary">حفظ</button></form>`);bindLookups(c,app.office);c.querySelector('form').onsubmit=async e=>{e.preventDefault();try{if(id)await app.office.saveFile(formData(e.target),id);else await app.office.createFile(formData(e.target),[]);closeModal();toast('تم حفظ الملف');app.refresh()}catch(z){toast(z.message,'error')}}}
async function caseForm(app,id){const old=id?await app.office.r.cases.get(id):{};const file=old.fileId?await app.office.r.files.get(old.fileId):null;const c=modal(`<div class="modal-tools"><button type="button" data-modal-back class="ghost">رجوع</button><button type="button" data-close class="modal-close">×</button></div><h2>${id?'تعديل':'إضافة'} قضية</h2><form id="case-form">${lookupField({name:'fileId',label:'الملف',store:'files',index:'fileNumber',value:old.fileId||'',displayValue:file?`${file.fileNumber||''} — ${file.title||''}`:''})}<label>رقم القضية<input name="caseNumber" required value="${esc(old.caseNumber||'')}"></label><label>السنة<input name="caseYear" inputmode="numeric" value="${esc(old.caseYear||new Date().getFullYear())}"></label><label>المحكمة<input name="courtId" value="${esc(old.courtId||'')}"></label><label>الدائرة<input name="chamber" value="${esc(old.chamber||'')}"></label><label>نوع القضية<input name="caseType" value="${esc(old.caseType||'')}"></label><label>الحالة<input name="status" value="${esc(old.status||'open')}"></label><label>تاريخ القيد<input type="date" name="filingDate" value="${esc(old.filingDate||'')}"></label><label>الموضوع<textarea name="subject">${esc(old.subject||'')}</textarea></label><button class="primary">حفظ</button></form>`);bindLookups(c,app.office);c.querySelector('form').onsubmit=async e=>{e.preventDefault();try{if(id)await app.office.saveCase(formData(e.target),id);else await app.office.createCase(formData(e.target),[]);closeModal();toast('تم حفظ القضية');app.refresh()}catch(z){toast(z.message,'error')}}}
async function genericForm(app,store,id=null){const map={hearings:['caseId','hearingDate','hearingTime','reason','whatHappened','decision','result','nextAction','nextHearingDate','notes'],procedures:['fileId','caseId','type','description','actionDate','assigneeId','status','priority','internalDueDate','notes','nextAction'],appointments:['fileId','clientId','title','date','time','location','type','status','notes'],communications:['clientId','fileId','channel','direction','subject','summary','date','followUpRequired','followUpDate'],caseNotes:['fileId','category','content'],opponents:['name','capacity','phone','address','notes'],powersOfAttorney:['clientId','fileId','poaNumber','type','issuedDate','expiryDate','scope','notes'],witnesses:['caseId','name','side','phone','address','notes'],expertReports:['caseId','expertName','reportDate','summary','notes'],judgments:['caseId','court','judgmentNumber','judgmentDate','operativeSummary','notes'],execution:['caseId','status','executionNumber','openedDate','stage','notes'],fees:['fileId','agreementType','agreedAmount','currency','paymentStatus','notes'],feePayments:['feeId','amount','date','note'],documentReferences:['fileId','title','type','physicalLocation','date','notes']}[store]||['title','date','status','notes'];const old=id?await app.office.r[store].get(id):{};const c=modal(`<div class="modal-tools"><button type="button" data-modal-back class="ghost">رجوع</button><button type="button" data-close class="modal-close">×</button></div><h2>${id?'تعديل':'إضافة'} سجل</h2><form id="generic-form">${fieldsHtml(map,old)}</form>`);bindLookups(c,app.office);c.querySelector('form').onsubmit=async e=>{e.preventDefault();try{await (await import('../services/generic.js')).saveGeneric(app.office,store,formData(e.target),id);closeModal();toast('تم الحفظ');app.refresh()}catch(z){toast(z.message,'error')}}}
function fieldsHtml(fields,old){return fields.map(f=>`<label>${esc(f)}${f==='notes'||f==='summary'||f==='content'||f==='operativeSummary'||f==='scope'?`<textarea name="${f}">${esc(old?.[f]||'')}</textarea>`:`<input name="${f}" value="${esc(old?.[f]||'')}" ${f.toLowerCase().includes('date')?'type="date"':''}>`}</label>`).join('')+'<button class="primary">حفظ</button>'}
