import {pager,pagingState,currentCursor,applyPageResult,nextPage,prevPage,resetPaging} from '../ui/pagination.js';
import {lookupField,bindLookups} from '../ui/lookup.js';
import {STORE} from '../db/schema.js';import {esc,formData} from '../ui/dom.js';import {normalizeArabic} from '../core/search-normalizer.js';import {modal,closeModal} from '../ui/modal.js';import {toast} from '../ui/toast.js';import {saveFee,addFeePayment} from '../services/finance.js';
const date=v=>v?new Date(v).toLocaleDateString('ar-EG'):'';
export async function dashboard(app){
 const {dashboardBrief}=await import('../services/dashboard.js');
 const r=await dashboardBrief(app.office);
 const d=v=>v?new Date(v).toLocaleDateString('ar-EG'):'';
 return `<div class="hero"><div><h2>صباح الخير، مكتب الأستاذ أحمد محمد خضير</h2><p>لوحة العمل اليومية والأسبوعية — الجلسات والأعمال التي تحتاج إلى متابعة.</p></div><div class="head-actions"><button class="ghost" data-back>رجوع</button><button class="primary" data-quick="file">+ فتح ملف جديد</button><button class="ghost" data-route="actionCenter">مركز العمل</button></div></div>
 <div class="dashboard-grid">
  <section class="panel priority-panel"><div class="panel-head"><h3>جلسات اليوم</h3><button class="link" data-dashboard-report="hearings|today">تقرير الجلسات</button></div>${r.todayHearings.length?r.todayHearings.slice(0,12).map(x=>`<div class="work-row"><b>${esc(x.hearingTime||'بدون وقت')}</b><span>${esc(x.reason||x.type||'جلسة')}</span><small>${d(x.hearingDate)}</small></div>`).join(''):'<p class="muted">لا توجد جلسات مسجلة اليوم.</p>'}</section>
  <section class="panel"><div class="panel-head"><h3>الأعمال الإدارية المتأخرة</h3><button class="link" data-dashboard-report="procedures|overdue">تقرير الأعمال</button></div>${r.overdueProcedures.length?r.overdueProcedures.slice(0,12).map(x=>`<div class="work-row"><b>${esc(x.internalDueDate||'')}</b><span>${esc(x.description||x.type||'إجراء')}</span><small>${esc(x.priority||'normal')}</small></div>`).join(''):'<p class="muted">لا توجد أعمال إدارية متأخرة.</p>'}</section>
  <section class="panel"><div class="panel-head"><h3>الجلسات القادمة</h3><button class="link" data-dashboard-report="hearings|week">هذا الأسبوع</button></div>${r.upcomingHearings.length?r.upcomingHearings.slice(0,12).map(x=>`<div class="work-row"><b>${d(x.hearingDate)}</b><span>${esc(x.hearingTime||'')} — ${esc(x.reason||x.type||'جلسة')}</span><small>${esc(x.caseNumber||'')}</small></div>`).join(''):'<p class="muted">لا توجد جلسات قادمة ضمن الفترة المعروضة.</p>'}</section>
  <section class="panel"><div class="panel-head"><h3>أعمال إدارية قادمة</h3><button class="link" data-dashboard-report="procedures|week">هذا الأسبوع</button></div>${r.upcomingProcedures.length?r.upcomingProcedures.slice(0,12).map(x=>`<div class="work-row"><b>${d(x.internalDueDate)}</b><span>${esc(x.description||x.type||'إجراء')}</span><small>${esc(x.status||'pending')}</small></div>`).join(''):'<p class="muted">لا توجد أعمال إدارية قادمة ضمن الفترة المعروضة.</p>'}</section>
 </div>
 <section class="panel daily-shortcuts"><div class="panel-head"><h3>تقارير العمل السريع</h3></div><div class="shortcut-grid"><button data-dashboard-report="hearings|tomorrow">جلسات غدًا</button><button data-dashboard-report="hearings|nextWeek">جلسات الأسبوع التالي</button><button data-dashboard-report="hearings|month">جلسات هذا الشهر</button><button data-dashboard-report="procedures|tomorrow">أعمال غدًا</button><button data-dashboard-report="procedures|nextWeek">أعمال الأسبوع التالي</button><button data-dashboard-report="procedures|month">أعمال هذا الشهر</button><button data-route-report="clients">الموكلون</button><button data-route-report="cases">القضايا</button></div></section></div>`
}
export async function clients(app){return pagedEntityPage(app,{store:STORE.clients,title:'الموكلون',description:'بيانات الموكلين في قاعدة البيانات الحالية.',addAttr:'data-add-client',addText:'إضافة موكل',index:'createdAt',dateField:'createdAt',statuses:['active','inactive'],render:clientTable})}
export async function files(app){return pagedEntityPage(app,{store:STORE.files,title:'الملفات',description:'الوحدة الإدارية الرئيسية لدورة العمل القانوني.',addAttr:'data-add-file',addText:'فتح ملف',index:'lastActivityAt',dateField:'lastActivityAt',statuses:['open','closed'],render:fileTable})}
export async function cases(app){return pagedEntityPage(app,{store:STORE.cases,title:'القضايا',description:'الوحدات القضائية المرتبطة بالملفات.',addAttr:'data-add-case',addText:'إضافة قضية',index:'filingDate',dateField:'filingDate',statuses:['open','closed','suspended','judged'],render:caseTable})}
const DEFAULT_FILTERS=()=>({q:'',status:'',priority:'',from:'',to:'',sort:'desc'});
async function pagedEntityPage(app,cfg){app.__pages=app.__pages||{};const state=pagingState(app.__pages[cfg.store],{filters:DEFAULT_FILTERS()});app.__pages[cfg.store]=state;state.filters={...DEFAULT_FILTERS(),...(state.filters||{})};const f=state.filters;const q=normalizeArabic(f.q);const filter=v=>{const text=normalizeArabic([v.fullName,v.nationalId,v.phone,v.phone1,v.fileNumber,v.title,v.caseNumber,v.caseYear,v.subject,v.courtId].filter(Boolean).join(' '));const ds=String(v[cfg.dateField]||v.updatedAt||v.createdAt||'').slice(0,10);return (!q||text.includes(q))&&(!f.status||v.status===f.status)&&(!f.priority||v.priority===f.priority)&&(!f.from||ds>=f.from)&&(!f.to||ds<=f.to)};const r=await app.office.listPage(cfg.store,{index:cfg.index,cursor:currentCursor(state),limit:25,direction:f.sort==='asc'?'next':'prev',filter});applyPageResult(state,r);return `<div class="page-head"><div><h2>${cfg.title}</h2><p>${cfg.description}</p></div><div class="head-actions"><button class="ghost" data-page-back>رجوع</button><button class="ghost" data-page-close>إغلاق</button><button class="primary" ${cfg.addAttr}>${cfg.addText}</button></div><div class="toolbar"><input id="${cfg.store}-q" value="${esc(f.q)}" placeholder="بحث سريع…" autocomplete="off"><details class="filter-tab"><summary>فرز وتصفية</summary><div class="mini-filter"><select data-filter-status><option value="">كل الحالات</option>${cfg.statuses.map(x=>`<option value="${x}">${x}</option>`).join('')}</select>${cfg.store===STORE.files?'<select data-filter-priority><option value="">كل الأولويات</option><option>normal</option><option>urgent</option><option>critical</option></select>':''}<input type="date" data-filter-from title="من"><input type="date" data-filter-to title="إلى"><select data-filter-sort><option value="desc">الأحدث أولًا</option><option value="asc">الأقدم أولًا</option></select></div></details><span class="muted">صفحة ${state.page}</span></div><div id="${cfg.store}-list" class="table-wrap">${r.items.length?cfg.render(r.items):`<p class="muted">${f.q||f.status||f.priority||f.from||f.to?'لا توجد سجلات مطابقة للبحث أو التصفية.':'لا توجد سجلات بعد. ابدأ بإضافة أول سجل.'}</p>`}</div>${pager({page:state.page,hasNext:state.hasNext,hasPrev:state.hasPrev})}`}
function clientTable(rows){return `<table><thead><tr><th>الاسم</th><th>الهاتف</th><th>الحالة</th><th>آخر تحديث</th><th></th></tr></thead><tbody>${rows.map(r=>`<tr data-status="${esc(r.status||'')}" data-date="${esc(r.updatedAt||'')}" data-search="${esc((r.fullName||'')+' '+(r.phone||r.phone1||''))}"><td><b>${esc(r.fullName)}</b></td><td>${esc(r.phone||r.phone1||'')}</td><td><span class="badge">${esc(r.status||'active')}</span></td><td>${date(r.updatedAt)}</td><td><button class="link" data-record-client="${r.id}">سجل</button> <button class="link" data-edit-client="${r.id}">تعديل</button></td></tr>`).join('')}</tbody></table>`}
function fileTable(rows){return `<table><thead><tr><th>رقم الملف</th><th>العنوان</th><th>الحالة</th><th>الأولوية</th><th>آخر نشاط</th><th></th></tr></thead><tbody>${rows.map(r=>`<tr data-status="${esc(r.status||'')}" data-priority="${esc(r.priority||'')}" data-date="${esc(r.lastActivityAt||'')}" data-search="${esc((r.fileNumber||'')+' '+(r.title||''))}"><td><b>${esc(r.fileNumber)}</b></td><td>${esc(r.title)}</td><td><span class="badge">${esc(r.status||'open')}</span></td><td>${esc(r.priority||'normal')}</td><td>${date(r.lastActivityAt)}</td><td><button class="link" data-record-file="${r.id}">سجل</button> <button class="link" data-edit-file="${r.id}">تعديل</button></td></tr>`).join('')}</tbody></table>`}
function caseTable(rows){return `<table><thead><tr><th>رقم/سنة</th><th>المحكمة</th><th>الموضوع</th><th>الحالة</th><th></th></tr></thead><tbody>${rows.map(r=>`<tr data-status="${esc(r.status||'')}" data-date="${esc(r.filingDate||'')}" data-search="${esc((r.caseNumber||'')+' '+(r.subject||'')+' '+(r.courtId||''))}"><td><b>${esc(r.caseNumber)}</b> / ${esc(r.caseYear)}</td><td>${esc(r.courtId||'')}</td><td>${esc(r.subject||'')}</td><td><span class="badge">${esc(r.status||'open')}</span></td><td><button class="link" data-record-case="${r.id}">سجل</button> <button class="link" data-edit-case="${r.id}">تعديل</button></td></tr>`).join('')}</tbody></table>`}
export async function search(app){return `<div class="page-head"><div><h2>البحث الموحد</h2><p>البحث في الموكلين والملفات والقضايا والخصوم.</p></div></div><div class="search-box"><input id="global-q" autofocus placeholder="اكتب اسمًا أو رقمًا أو عنوانًا…"><div id="search-results"></div></div>`}
export async function genericPage(app,store,title){
 const fields={hearings:['caseId','hearingDate','hearingTime','reason','result'],procedures:['description','actionDate','internalDueDate','status','priority'],appointments:['title','date','time','location','status'],communications:['channel','direction','subject','date','summary'],caseNotes:['category','content'],opponents:['name','capacity','phone','address'],powersOfAttorney:['poaNumber','type','issuedDate','expiryDate','scope'],witnesses:['name','side','phone','address'],expertReports:['expertName','reportDate','summary'],judgments:['judgmentNumber','court','judgmentDate','operativeSummary'],execution:['executionNumber','status','stage','openedDate'],fees:['fileId','agreementType','agreedAmount','currency','paymentStatus'],feePayments:['feeId','amount','date'],documentReferences:['title','type','physicalLocation','date']}[store]||['title','date','status','notes'];
 const indexMap={hearings:'hearingDate',procedures:'internalDueDate',appointments:'date',communications:'date',caseNotes:'createdAt',opponents:'nameNormalized',powersOfAttorney:'issuedDate',witnesses:'createdAt',expertReports:'reportDate',judgments:'judgmentDate',execution:'openedDate',fees:null,feePayments:'date',documentReferences:'date'};
 app.__genericPages=app.__genericPages||{};const state=pagingState(app.__genericPages[store]);app.__genericPages[store]=state;
 const r=await app.office.listPage(store,{index:indexMap[store],cursor:currentCursor(state),limit:25,direction:'prev'});applyPageResult(state,r);
 const labels={fileId:'الملف',agreementType:'نوع الاتفاق',agreedAmount:'المبلغ المتفق عليه',currency:'العملة',paymentStatus:'حالة السداد',feeId:'الأتعاب',amount:'المبلغ',date:'التاريخ',title:'العنوان',type:'النوع',physicalLocation:'مكان الحفظ'};
 const files=fields.includes('fileId')?await app.office.r.files.getMany(r.items.map(x=>x.fileId)):[];const fm=new Map(files.map(x=>[x.id,`${x.fileNumber||''} — ${x.title||''}`]));
 let paid=new Map();if(store==='fees')paid=new Map(await Promise.all(r.items.map(async x=>[x.id,await app.office.r.feePayments.sumByIndex('feeId',x.id,'amount')])));
 const cell=(f,x)=>f==='fileId'?esc(fm.get(x[f])||'—'):esc(x[f]??'');
 const cols=store==='fees'?[...fields,'__paid']:fields;
 return `<div class="page-head"><div><h2>${title}</h2><p>صفحة ${state.page} · يتم تحميل السجلات المطلوبة فقط.</p></div><div class="head-actions"><button class="ghost" data-page-back>رجوع</button><button class="ghost" data-page-close>إغلاق</button><button class="primary" data-generic-add="${store}">إضافة</button></div></div><div class="table-wrap"><table><thead><tr>${cols.map(f=>`<th>${esc(f==='__paid'?'المدفوع':labels[f]||f)}</th>`).join('')}<th></th></tr></thead><tbody>${r.items.length?r.items.map(x=>`<tr>${cols.map(f=>`<td>${f==='__paid'?esc((paid.get(x.id)||0).toLocaleString('ar-EG')):cell(f,x)}</td>`).join('')}<td><button class="link" data-generic-edit="${store}|${x.id}">تعديل</button>${store==='fees'?` <button class="link" data-fee-pay="${x.id}">تسجيل دفعة</button>`:''}</td></tr>`).join(''):`<tr><td colspan="${cols.length+1}" class="muted">لا توجد سجلات بعد.</td></tr>`}</tbody></table></div>${pager({page:state.page,hasNext:state.hasNext,hasPrev:state.hasPrev})}`}
export function bindGenericPagePagination(app,store){const st=app.__genericPages?.[store];document.querySelector('[data-pager-next]')?.addEventListener('click',()=>{if(nextPage(st))app.refresh()});document.querySelector('[data-pager-prev]')?.addEventListener('click',()=>{if(prevPage(st))app.refresh()});document.querySelector(`[data-generic-add="${store}"]`)?.addEventListener('click',()=>genericForm(app,store));document.querySelectorAll('[data-generic-edit]').forEach(b=>b.onclick=()=>{const [s,id]=b.dataset.genericEdit.split('|');genericForm(app,s,id)});document.querySelectorAll('[data-fee-pay]').forEach(b=>b.onclick=()=>feePaymentForm(app,b.dataset.feePay))}
export function bindDashboard(app){
 document.querySelector('[data-quick=\"file\"]')?.addEventListener('click',()=>app.go('files'));
 document.querySelector('[data-back]')?.addEventListener('click',()=>app.back());
 document.querySelectorAll('[data-dashboard-report]').forEach(b=>b.onclick=()=>{const [type,preset]=b.dataset.dashboardReport.split('|');app.go('reports?type='+encodeURIComponent(type)+'&preset='+encodeURIComponent(preset))});
 document.querySelectorAll('[data-route-report]').forEach(b=>b.onclick=()=>app.go('reports?type='+encodeURIComponent(b.dataset.routeReport)));
}
export function bindPages(app){
 document.querySelector('[data-back]')?.addEventListener('click',()=>app.back());
 document.querySelector('[data-add-client]')?.addEventListener('click',()=>clientForm(app));document.querySelector('[data-add-file]')?.addEventListener('click',()=>fileForm(app));document.querySelector('[data-add-case]')?.addEventListener('click',()=>caseForm(app));
 bindRecordButtons(app);document.querySelectorAll('[data-edit-client]').forEach(b=>b.onclick=()=>clientForm(app,b.dataset.editClient));document.querySelectorAll('[data-edit-file]').forEach(b=>b.onclick=()=>fileForm(app,b.dataset.editFile));document.querySelectorAll('[data-edit-case]').forEach(b=>b.onclick=()=>caseForm(app,b.dataset.editCase));
 const store=app.route.split('?')[0];const st=app.__pages?.[store];if(!st)return;
 const q=document.querySelector('#'+store+'-q');let timer=0;q?.addEventListener('input',()=>{clearTimeout(timer);timer=setTimeout(()=>{st.filters.q=q.value;resetPaging(st);app.refresh()},300)});
 bindListFilter(app,store);
 document.querySelector('[data-pager-next]')?.addEventListener('click',()=>{if(nextPage(st))app.refresh()});
 document.querySelector('[data-pager-prev]')?.addEventListener('click',()=>{if(prevPage(st))app.refresh()});
}
function bindRecordButtons(app){document.querySelectorAll('[data-record-client]').forEach(b=>b.onclick=()=>app.go('client:'+b.dataset.recordClient));document.querySelectorAll('[data-record-file]').forEach(b=>b.onclick=()=>app.go('file:'+b.dataset.recordFile));document.querySelectorAll('[data-record-case]').forEach(b=>b.onclick=()=>app.go('case:'+b.dataset.recordCase))}
function bindListFilter(app,store){const st=app.__pages[store];document.querySelectorAll('.filter-tab select,.filter-tab input').forEach(el=>{const ds=el.dataset;const key='filterStatus' in ds?'status':'filterPriority' in ds?'priority':'filterFrom' in ds?'from':'filterTo' in ds?'to':'filterSort' in ds?'sort':null;if(!key)return;el.value=st.filters[key]||(key==='sort'?'desc':'');el.addEventListener('change',()=>{st.filters[key]=el.value;resetPaging(st);app.refresh()})})}
const modalTools='<div class="modal-tools"><button type="button" data-modal-back class="ghost">رجوع</button><button type="button" data-close class="modal-close">×</button></div>';
async function linkedClientsHtml(app,store,key,id){if(!id)return '';const links=await app.office.r[store].byIndex(key,id,100);const cs=await app.office.r.clients.getMany(links.map(x=>x.clientId));return cs.length?`<p class="muted">الموكلون المرتبطون: ${cs.map(c=>esc(c.fullName)).join('، ')}</p>`:''}
export async function clientForm(app,id){const x=id?await app.office.r.clients.get(id)||{}:{};const c=modal(`${modalTools}<h2>${id?'تعديل':'إضافة'} موكل</h2><form id="client-form"><label>الاسم الكامل<input name="fullName" required value="${esc(x.fullName||'')}"></label><label>الرقم القومي<input name="nationalId" inputmode="numeric" maxlength="14" value="${esc(x.nationalId||'')}"></label><label>الهاتف<input name="phone" type="tel" value="${esc(x.phone||'')}"></label><label>العنوان<textarea name="address">${esc(x.address||'')}</textarea></label><label>المهنة<input name="profession" value="${esc(x.profession||'')}"></label><label>الحالة<select name="status"><option value="active" ${x.status!=='inactive'?'selected':''}>نشط</option><option value="inactive" ${x.status==='inactive'?'selected':''}>غير نشط</option></select></label><label>ملاحظات<textarea name="notes">${esc(x.notes||'')}</textarea></label><button class="primary">حفظ</button></form>`);c.querySelector('form').onsubmit=async e=>{e.preventDefault();try{await app.office.saveClient(formData(e.target),id,id?x.version:null);closeModal();toast('تم حفظ الموكل');app.refresh()}catch(z){toast(errorText(z),'error')}}}
export async function fileForm(app,id,preset={}){const old=id?await app.office.r.files.get(id)||{}:{};const presetClient=preset.clientId?await app.office.r.clients.get(preset.clientId):null;const c=modal(`${modalTools}<h2>${id?'تعديل':'فتح'} ملف</h2><form id="file-form"><label>عنوان الملف<input name="title" required value="${esc(old.title||'')}"></label><label>نوع العمل<input name="workType" value="${esc(old.workType||'')}"></label><label>الحالة<select name="status"><option value="open">مفتوح</option><option value="closed" ${old.status==='closed'?'selected':''}>مغلق</option></select></label><label>المرحلة<input name="stage" value="${esc(old.stage||'')}"></label><label>الأولوية<select name="priority"><option>normal</option><option ${old.priority==='urgent'?'selected':''}>urgent</option><option ${old.priority==='critical'?'selected':''}>critical</option></select></label><label>تاريخ الفتح<input type="date" name="openedAt" value="${esc(old.openedAt||localToday())}"></label><label>الخطوة التالية<input name="nextStep" value="${esc(old.nextStep||'')}"></label><label>تاريخ الخطوة التالية<input type="date" name="nextStepDate" value="${esc(old.nextStepDate||'')}"></label><label>ملاحظات<textarea name="notes">${esc(old.notes||'')}</textarea></label>${await linkedClientsHtml(app,STORE.fileClients,'fileId',id)}${lookupField({name:'__clientId',label:id?'ربط موكل إضافي (اختياري)':'الموكل (اختياري)',store:'clients',index:'fullNameNormalized',value:presetClient?.id||'',displayValue:presetClient?.fullName||''})}<button class="primary">حفظ</button></form>`);bindLookups(c,app.office);c.querySelector('form').onsubmit=async e=>{e.preventDefault();try{const data=formData(e.target);const clientId=data.__clientId;delete data.__clientId;if(id){await app.office.saveFile(data,id,old.version);if(clientId)await app.office.addLink(STORE.fileClients,id,clientId)}else await app.office.createFile(data,clientId?[clientId]:[]);closeModal();toast('تم حفظ الملف');app.refresh()}catch(z){toast(errorText(z),'error')}}}
export async function caseForm(app,id,preset={}){const old=id?await app.office.r.cases.get(id)||{}:{};const fileId=old.fileId||preset.fileId||'';const file=fileId?await app.office.r.files.get(fileId):null;const c=modal(`${modalTools}<h2>${id?'تعديل':'إضافة'} قضية</h2><form id="case-form">${lookupField({name:'fileId',label:'الملف',store:'files',index:'fileNumber',value:fileId,displayValue:file?`${file.fileNumber||''} — ${file.title||''}`:''})}<label>رقم القضية<input name="caseNumber" required value="${esc(old.caseNumber||'')}"></label><label>السنة<input name="caseYear" inputmode="numeric" value="${esc(old.caseYear||new Date().getFullYear())}"></label><label>المحكمة<input name="courtId" value="${esc(old.courtId||'')}"></label><label>الدائرة<input name="chamber" value="${esc(old.chamber||'')}"></label><label>نوع القضية<input name="caseType" value="${esc(old.caseType||'')}"></label><label>الحالة<select name="status">${['open','suspended','judged','closed'].map(x=>`<option ${x===(old.status||'open')?'selected':''}>${x}</option>`).join('')}</select></label><label>تاريخ القيد<input type="date" name="filingDate" value="${esc(old.filingDate||'')}"></label><label>الموضوع<textarea name="subject">${esc(old.subject||'')}</textarea></label>${await linkedClientsHtml(app,STORE.caseClients,'caseId',id)}${lookupField({name:'__clientId',label:id?'ربط موكل إضافي (اختياري)':'الموكل (اختياري)',store:'clients',index:'fullNameNormalized'})}<button class="primary">حفظ</button></form>`);bindLookups(c,app.office);c.querySelector('form').onsubmit=async e=>{e.preventDefault();try{const data=formData(e.target);const clientId=data.__clientId;delete data.__clientId;if(!data.fileId)throw new Error('اختر الملف من القائمة المقترحة.');if(id){await app.office.saveCase(data,id,old.version);if(clientId)await app.office.addLink(STORE.caseClients,id,clientId)}else await app.office.createCase(data,clientId?[clientId]:[]);closeModal();toast('تم حفظ القضية');app.refresh()}catch(z){toast(errorText(z),'error')}}}
const GENERIC_FIELDS={fees:['fileId','agreementType','agreedAmount','currency','paymentStatus','notes'],feePayments:['feeId','amount','date','note'],documentReferences:['fileId','title','type','physicalLocation','date','notes']};
const GENERIC_LABELS={fileId:'الملف',agreementType:'نوع الاتفاق',agreedAmount:'المبلغ المتفق عليه',currency:'العملة',paymentStatus:'حالة السداد',notes:'ملاحظات',feeId:'الأتعاب',amount:'المبلغ',date:'التاريخ',note:'ملاحظة',title:'العنوان',type:'النوع',physicalLocation:'مكان الحفظ'};
async function genericForm(app,store,id=null){const fields=GENERIC_FIELDS[store]||['title','date','status','notes'];const old=id?await app.office.r[store].get(id)||{}:{};const file=old.fileId?await app.office.r.files.get(old.fileId):null;const c=modal(`${modalTools}<h2>${id?'تعديل':'إضافة'} سجل</h2><form id="generic-form">${fieldsHtml(fields,old,file)}</form>`);bindLookups(c,app.office);c.querySelector('form').onsubmit=async e=>{e.preventDefault();try{const data=formData(e.target);if(store==='fees')await saveFee(app.office,data,id);else if(store==='feePayments'&&!id)await addFeePayment(app.office,data);else{if(fields.includes('fileId')&&!data.fileId)throw new Error('اختر الملف من القائمة المقترحة.');await (await import('../services/generic.js')).saveGeneric(app.office,store,data,id)}closeModal();toast('تم الحفظ');app.refresh()}catch(z){toast(errorText(z),'error')}}}
async function feePaymentForm(app,feeId){const fee=await app.office.r.fees.get(feeId);if(!fee)return toast('الأتعاب غير موجودة','error');const paid=await app.office.r.feePayments.sumByIndex('feeId',feeId,'amount');const remaining=Math.max(0,Number(fee.agreedAmount||0)-paid);const c=modal(`${modalTools}<h2>تسجيل دفعة أتعاب</h2><p class="muted">المتفق عليه: ${Number(fee.agreedAmount||0).toLocaleString('ar-EG')} — المدفوع: ${paid.toLocaleString('ar-EG')} — المتبقي: ${remaining.toLocaleString('ar-EG')}</p><form><input type="hidden" name="feeId" value="${esc(feeId)}"><label>المبلغ<input name="amount" type="number" min="0.01" step="0.01" max="${remaining}" required></label><label>التاريخ<input name="date" type="date" value="${localToday()}" required></label><label>ملاحظة<input name="note"></label><button class="primary">حفظ الدفعة</button></form>`);c.querySelector('form').onsubmit=async e=>{e.preventDefault();try{await addFeePayment(app.office,formData(e.target));closeModal();toast('تم تسجيل الدفعة');app.refresh()}catch(z){toast(errorText(z),'error')}}}
function fieldsHtml(fields,old,file){return fields.map(f=>{const label=GENERIC_LABELS[f]||f;const v=old?.[f]??'';if(f==='fileId')return lookupField({name:'fileId',label,store:'files',index:'fileNumber',value:v,displayValue:file?`${file.fileNumber||''} — ${file.title||''}`:''});if(['notes','summary','content','operativeSummary','scope'].includes(f))return `<label>${esc(label)}<textarea name="${f}">${esc(v)}</textarea></label>`;const type=f.toLowerCase().includes('date')?'date':['agreedAmount','amount'].includes(f)?'number':'text';return `<label>${esc(label)}<input name="${f}" type="${type}" ${type==='number'?'min="0" step="0.01"':''} value="${esc(v)}"></label>`}).join('')+'<button class="primary">حفظ</button>'}
function errorText(e){const d=e?.details;if(d&&typeof d==='object'&&!(d instanceof Error)){const msgs=Object.values(d).filter(x=>typeof x==='string');if(msgs.length)return `${e.message} ${msgs.join('، ')}`}return e?.message||'تعذر الحفظ'}
function localToday(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
