import {STORE} from '../db/schema.js';
import {esc} from '../ui/dom.js';
import {buildFileTimeline,buildCaseTimeline,d,dt} from '../services/timeline.js';

async function links(office,store,index,key){return office.r[store].byIndex(index,key,500)}
const escv=v=>esc(v==null?'':String(v));
function navActions(){return `<div class="head-actions"><button class="ghost" data-page-back>رجوع</button><button class="ghost" data-page-close>إغلاق</button></div>`}
function timelineHtml(items){return items.length?items.map(x=>`<div class="timeline-item"><div class="timeline-top"><span class="timeline-type">${escv(x.type)}</span><small>${dt(x.date)}</small></div><b>${escv(x.title)}</b>${x.detail?`<p>${escv(x.detail)}</p>`:''}</div>`).join(''):'<p class="muted">لا يوجد نشاط مسجل.</p>'}
function queueBox(last,next){return `<section class="work-queue"><div><span class="eyebrow">آخر نشاط</span><b>${last?escv(last.title):'لا يوجد'}</b><small>${last?dt(last.date):'—'}</small></div><div><span class="eyebrow">القادم</span><b>${next?escv(next.title):'لا يوجد موعد محدد'}</b><small>${next?dt(next.date):'—'}</small></div></section>`}

export async function clientRecord(app,id){
 const c=await app.office.r.clients.get(id);if(!c)return `<div class="error-box"><h2>الموكل غير موجود</h2>${navActions()}</div>`;
 const [fl,cc,poa]=await Promise.all([links(app.office,STORE.fileClients,'clientId',id),links(app.office,STORE.caseClients,'clientId',id),links(app.office,STORE.powersOfAttorney,'clientId',id)]);
 const [files,cases]=await Promise.all([app.office.r.files.getMany(fl.map(x=>x.fileId)),app.office.r.cases.getMany(cc.map(x=>x.caseId))]);
 const fileMap=new Map(files.map(x=>[x.id,x]));
 const caseMap=new Map(cases.map(x=>[x.id,x]));
 return `<div class="record-head"><div><span class="eyebrow">سجل الموكل</span><h2>${escv(c.fullName)}</h2><p>${escv(c.phone||c.phone1||c.phones?.[0]||'')} ${c.nationalId?'— الرقم القومي: '+escv(c.nationalId):''}</p></div>${navActions()}</div><div class="cards"><div class="stat"><b>${fl.length}</b><span>ملفات مرتبطة</span></div><div class="stat"><b>${cc.length}</b><span>قضايا مرتبطة</span></div><div class="stat"><b>${poa.length}</b><span>توكيلات</span></div></div><section class="panel"><h3>البيانات</h3><div class="grid2"><p><b>العنوان:</b> ${escv(c.address||'—')}</p><p><b>المهنة:</b> ${escv(c.profession||'—')}</p><p><b>الحالة:</b> ${escv(c.status||'active')}</p><p><b>ملاحظات:</b> ${escv(c.notes||'—')}</p></div></section><section class="panel"><div class="section-head"><h3>الملفات المرتبطة</h3><button class="primary" data-open-file-for-client="${escv(id)}">+ فتح ملف</button></div>${fl.length?fl.map(x=>{const f=fileMap.get(x.fileId);return `<button class="result" data-record-file="${escv(x.fileId)}"><b>${escv(f?.fileNumber||'ملف')}</b> — ${escv(f?.title||x.fileId)} <small>${escv(f?.status||'')}</small></button>`}).join(''):'<p class="muted">لا توجد ملفات مرتبطة.</p>'}</section><section class="panel"><h3>القضايا المرتبطة</h3>${cc.length?cc.map(x=>{const k=caseMap.get(x.caseId);return `<button class="result" data-record-case="${escv(x.caseId)}"><b>${escv(k?.caseNumber||'قضية')}</b> / ${escv(k?.caseYear||'')} — ${escv(k?.subject||k?.courtId||x.caseId)}</button>`}).join(''):'<p class="muted">لا توجد قضايا مرتبطة.</p>'}</section><section class="panel"><h3>التوكيلات</h3>${poa.length?poa.map(x=>`<div class="row"><b>${escv(x.poaNumber||'توكيل')}</b><small>${escv(x.type||'')} — ${d(x.issuedDate)} ${x.expiryDate?'— ينتهي '+d(x.expiryDate):''}</small></div>`).join(''):'<p class="muted">لا توجد توكيلات.</p>'}</section>`
}

export async function fileRecord(app,id){
 const data=await buildFileTimeline(app.office,id);if(!data)return `<div class="error-box"><h2>الملف غير موجود</h2>${navActions()}</div>`;
 const {file:f,cases:cs,timeline,last,future,counts}=data;
 const [fc,docs,fees]=await Promise.all([links(app.office,STORE.fileClients,'fileId',id),links(app.office,STORE.documentReferences,'fileId',id),links(app.office,STORE.fees,'fileId',id)]);
 const clients=await app.office.r.clients.getMany(fc.map(x=>x.clientId));
 const totalFees=fees.reduce((n,x)=>n+Number(x.agreedAmount||0),0);
 return `<div class="record-head"><div><span class="eyebrow">سجل الملف</span><h2>${escv(f.fileNumber)} — ${escv(f.title)}</h2><p>${escv(f.workType||'')} · ${escv(f.status||'open')} · أولوية ${escv(f.priority||'normal')}</p></div>${navActions()}</div>${queueBox(last,future)}<div class="cards"><div class="stat"><b>${cs.length}</b><span>قضايا</span></div><div class="stat"><b>${clients.length}</b><span>موكلون</span></div><div class="stat"><b>${counts.hearings}</b><span>جلسات</span></div><div class="stat"><b>${counts.procedures}</b><span>إجراءات</span></div><div class="stat"><b>${totalFees.toLocaleString('ar-EG')}</b><span>أتعاب متفق عليها</span></div></div><section class="panel"><h3>العمل الحالي</h3><div class="grid2"><p><b>المرحلة:</b> ${escv(f.stage||'—')}</p><p><b>الخطوة التالية:</b> ${escv(f.nextStep||'—')}</p><p><b>تاريخ الخطوة:</b> ${d(f.nextStepDate)}</p><p><b>آخر نشاط:</b> ${d(f.lastActivityAt)}</p></div><p><b>ملاحظات:</b> ${escv(f.notes||'—')}</p></section><section class="panel"><div class="section-head"><h3>الموكلون</h3></div>${clients.map(c=>`<button class="result" data-record-client="${escv(c.id)}">${escv(c.fullName)}</button>`).join('')||'<p class="muted">لا يوجد موكلون.</p>'}</section><section class="panel"><h3>القضايا</h3>${cs.map(c=>`<button class="result" data-record-case="${escv(c.id)}">${escv(c.caseNumber||'')} / ${escv(c.caseYear||'')} — ${escv(c.subject||'')}</button>`).join('')||'<p class="muted">لا توجد قضايا.</p>'}</section><section class="panel"><h3>المسار الزمني الموحد</h3><p class="muted">يجمع النشاط التشغيلي والقضائي المرتبط بالملف في مسار واحد.</p>${timelineHtml(timeline)}</section><section class="panel"><h3>مراجع المستندات</h3>${docs.length?docs.map(x=>`<div class="row"><b>${escv(x.title||'مرجع')}</b><small>${escv(x.type||'')} — ${d(x.date)} — ${escv(x.physicalLocation||'')}</small></div>`).join(''):'<p class="muted">لا توجد مراجع.</p>'}</section>`
}

export async function caseRecord(app,id){
 const data=await buildCaseTimeline(app.office,id);if(!data)return `<div class="error-box"><h2>القضية غير موجودة</h2>${navActions()}</div>`;
 const {case:c,timeline,last,future,counts}=data;
 const [cc,co]=await Promise.all([links(app.office,STORE.caseClients,'caseId',id),links(app.office,STORE.caseOpponents,'caseId',id)]);
 const [clients,opponents,file]=await Promise.all([app.office.r.clients.getMany(cc.map(x=>x.clientId)),app.office.r.opponents.getMany(co.map(x=>x.opponentId)),app.office.r.files.get(c.fileId)]);
 return `<div class="record-head"><div><span class="eyebrow">سجل القضية</span><h2>${escv(c.caseNumber)} / ${escv(c.caseYear)} — ${escv(c.subject||'دون موضوع')}</h2><p>${escv(c.courtId||'')} · ${escv(c.chamber||'')} · ${escv(c.status||'')}</p></div>${navActions()}</div>${queueBox(last,future)}<div class="cards"><div class="stat"><b>${clients.length}</b><span>موكلون</span></div><div class="stat"><b>${opponents.length}</b><span>خصوم</span></div><div class="stat"><b>${counts.hearings}</b><span>جلسات</span></div><div class="stat"><b>${counts.procedures}</b><span>إجراءات</span></div><div class="stat"><b>${counts.judgments}</b><span>أحكام</span></div><div class="stat"><b>${counts.execution}</b><span>تنفيذ</span></div></div><section class="panel"><h3>الملف الأب</h3><button class="result" data-record-file="${escv(c.fileId)}">${escv(file?.fileNumber||c.fileId)} — ${escv(file?.title||'')}</button></section><div class="grid2"><section class="panel"><h3>الموكلون</h3>${clients.map(x=>`<button class="result" data-record-client="${escv(x.id)}">${escv(x.fullName)}</button>`).join('')||'<p class="muted">لا يوجد.</p>'}</section><section class="panel"><h3>الخصوم</h3>${opponents.map(x=>`<div class="row"><b>${escv(x.name)}</b><small>${escv(x.capacity||'')}</small></div>`).join('')||'<p class="muted">لا يوجد.</p>'}</section></div><section class="panel"><h3>المسار الزمني للقضية</h3>${timelineHtml(timeline)}</section>`
}

export function bindRecords(app){document.querySelectorAll('[data-record-client]').forEach(b=>b.onclick=()=>app.go('client:'+b.dataset.recordClient));document.querySelectorAll('[data-record-file]').forEach(b=>b.onclick=()=>app.go('file:'+b.dataset.recordFile));document.querySelectorAll('[data-record-case]').forEach(b=>b.onclick=()=>app.go('case:'+b.dataset.recordCase));document.querySelector('[data-open-file-for-client]')?.addEventListener('click',()=>app.go('files'));}
